### ISSUE TITLE
iocsh scripts should pass P macro instead of PREFIX to create_monitor_set calls

### ISSUE THREAD

**Issue by kmpeters** [epics-modules/autosave#20]
The calls to create_monitor_set for built_*.req:
https://github.com/epics-modules/autosave/blob/master/iocsh/autosaveBuild.iocsh#L21

And the calls to create_montior_set for the user-specified req files (usually auto_*.req):
https://github.com/epics-modules/autosave/blob/master/iocsh/save_restore.iocsh#L27

All set PREFIX=$(PREFIX), but they should very likely be setting P=$(PREFIX), since the P is the standard prefix macro for most EPICS databases.

**Comment by kmpeters** [comment]
I'm not sure if this is actually necessary, but I think it eliminates an error message.

**Comment by keenanlang** [comment]
fixed in 227ad60
