### ISSUE TITLE
Autosave 5.10: IOC crashes on zero-argument call to reload_manual_set

### ISSUE THREAD

**Issue by daykin** [epics-modules/autosave#31]
Zero-argument IOC shell call to reload_manual_set results in IOC being killed by SIGSEGV.

`epics>reload_manual_set
@@@ Current time: Fri Jan  3 15:03:05 2020
@@@ Child process is shutting down, auto restart is disabled
@@@ ^R or ^X restarts the child, ^Q quits the server

@@@ @@@ @@@ @@@ @@@
@@@ Received a sigChild for process 26535. The process was killed by signal 11
@@@ Restarting child "ls1-rf-llrf"
@@@    (as /usr/local/lib/iocapps/ls1-rf-llrf/iocBoot/iocls1-rf-llrf/st.cmd)
@@@ The PID of new child "ls1-rf-llrf" is: 27199
@@@ @@@ @@@ @@@ @@@
`

**Comment by anjohnson** [comment]
Agreed, it looks like many of the autosave IOC shell commands are likely to seg-fault when given a NULL char* argument (which is what an omitted argument becomes), although some do appear to be protected against that.
